GET http://localhost:5065/games

###

GET http://localhost:5065/games/3

###

POST http://localhost:5065/games
Content-Type: application/json

{
    "Name":"Jhonny",
    "GenreId":2,
    "Price":12.55,
    "ReleaseDate": "2011-11-18"
}

###

PUT http://localhost:5065/games/2
Content-Type: application/json

{
    "name":"Roblox",
    "genreId":2,
    "price":10,
    "releaseDate": "2017-11-18"
}

###

DELETE http://localhost:5065/games/1